const residences = [
  {
    id: 1,
    sold: "yes",
    purchased_by: "Surriya Perveen",
    title: "",
    size: "202",
    floor: "Lower Ground Floor",
    number: "1",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-01.jpg",
  },
  {
    id: 2,
    sold: "yes",
    purchased_by: "Imran Ali",
    title: "",
    size: "202",
    floor: "Lower Ground Floor",
    number: "2",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-02.jpg",
  },
  {
    id: 3,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "292",
    floor: "Lower Ground Floor",
    number: "3",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-03.jpg",
  },
  {
    id: 4,
    sold: "yes",
    purchased_by: "Sahil Yashib",
    title: "",
    size: "315",
    floor: "Lower Ground Floor",
    number: "4",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-04.jpg",
  },
  {
    id: 5,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "309",
    floor: "Lower Ground Floor",
    number: "5",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-05.jpg",
  },
  {
    id: 6,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "360",
    floor: "Lower Ground Floor",
    number: "6",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-06-2.png",
  },
  {
    id: 7,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "454",
    floor: "Lower Ground Floor",
    number: "7",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-07.jpg",
  },
  {
    id: 8,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "542",
    floor: "Lower Ground Floor",
    number: "8",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/lg-08.jpg",
  },
  {
    id: 9,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "683",
    floor: "Ground Floor",
    number: "1",
    type: "Office",
    image: "/images/dsa/residences/ground/off-01.jpg",
  },
  {
    id: 10,
    sold: "yes",
    purchased_by: "Zahir ul Haq",
    title: "",
    size: "734",
    floor: "Ground Floor",
    number: "2",
    type: "Office",
    image: "/images/dsa/residences/ground/off-02.jpg",
  },
  {
    id: 11,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "",
    size: "819",
    floor: "Ground Floor",
    number: "3",
    type: "Office",
    image: "/images/dsa/residences/ground/off-03.jpg",
  },

  {
    id: 12,
    sold: "yes",
    purchased_by: "Zeeshan Yousaf",
    title: "",
    size: "284",
    floor: "1st Floor",
    number: "1",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-01.jpg",
  },
  {
    id: 13,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "306",
    floor: "1st Floor",
    number: "2",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-02.jpg",
  },
  {
    id: 14,
    sold: "yes",
    purchased_by: "Faryad Ali",
    title: "",
    size: "310",
    floor: "1st Floor",
    number: "3",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-03.jpg",
  },
  {
    id: 15,
    sold: "yes",
    purchased_by: "Zain Saleem",
    title: "",
    size: "330",
    floor: "1st Floor",
    number: "4",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-04.jpg",
  },
  {
    id: 16,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "490",
    floor: "1st Floor",
    number: "5",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-05.jpg",
  },
  {
    id: 17,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "516",
    floor: "1st Floor",
    number: "6",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-06.jpg",
  },
  {
    id: 18,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "631",
    floor: "1st Floor",
    number: "7",
    type: "Shop",
    image: "/images/dsa/residences/first/ff-07.jpg",
  },

  {
    id: 19,
    sold: "yes",
    purchased_by: "Mujahid Farooqi",
    title: "One Bed Deluxe",
    size: "625",
    floor: "2nd Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/second/OneBedDeluxe(596sqft).png",
  },
  {
    id: 20,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "One Bed Executive",
    size: "573",
    floor: "2nd Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/second/OneBedExecutive(575sqft).png",
  },
  {
    id: 21,
    sold: "yes",
    purchased_by: "Shabaz Tariq",
    title: "One Bed Executive",
    size: "595",
    floor: "2nd Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/second/OneBedExecutive(593sqft).png",
  },
  {
    id: 22,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "Studio Deluxe",
    size: "387",
    floor: "2nd Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/second/StudioDeluxe(369sqft).png",
  },
  {
    id: 23,
    sold: "yes",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "410",
    floor: "2nd Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/second/StudioDeluxe(391sqft).png",
  },
  {
    id: 24,
    sold: "yes",
    purchased_by: "Ali Imran",
    title: "Studio Executive",
    size: "360",
    floor: "2nd Floor",
    number: "6",
    type: "Apartment",
    image: "/images/dsa/residences/second/StudioExecutive(350sqft).png",
  },

  {
    id: 25,
    sold: "noyes",
    purchased_by: "Muhammad Bilal Javed",
    title: "One Bed Deluxe",
    size: "625",
    floor: "3rd Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/third/OneBedDeluxe(596sqft).png",
  },
  {
    id: 26,
    sold: "yes",
    purchased_by: "Inam Ul Haq",
    title: "One Bed Executive",
    size: "573",
    floor: "3rd Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/third/OneBedExecutive(575sqft).png",
  },
  {
    id: 27,
    sold: "yes",
    purchased_by: "Jehad Khan",
    title: "One Bed Executive",
    size: "595",
    floor: "3rd Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/third/OneBedExecutive(593sqft).png",
  },

  {
    id: 28,
    sold: "yes",
    purchased_by: "Muhammad Saqib",
    title: "Studio Deluxe",
    size: "387",
    floor: "3rd Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/third/StudioDeluxe(369sqft).png",
  },
  {
    id: 29,
    sold: "yes",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "410",
    floor: "3rd Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/third/StudioDeluxe(391sqft).png",
  },
  {
    id: 30,
    sold: "yes",
    purchased_by: "Imran Bin Ali",
    title: "Studio Executive",
    size: "360",
    floor: "3rd Floor",
    number: "6",
    type: "Apartment",
    image: "/images/dsa/residences/third/StudioExecutive(350sqft).png",
  },

  {
    id: 31,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "625",
    floor: "4th Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/OneBedDeluxe(596sqft).png",
  },
  {
    id: 32,
    sold: "yes",
    purchased_by: "Aziz ur Rehman",
    title: "One Bed Executive",
    size: "573",
    floor: "4th Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/OneBedExecutive(575sqft).png",
  },
  {
    id: 33,
    sold: "yes",
    purchased_by: "M. Sohail Khan",
    title: "One Bed Executive",
    size: "595",
    floor: "4th Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/OneBedExecutive(593sqft).png",
  },
  {
    id: 34,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "387",
    floor: "4th Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/StudioDeluxe(369sqft).png",
  },
  {
    id: 35,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "410",
    floor: "4th Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/StudioDeluxe(391sqft).png",
  },
  {
    id: 36,
    sold: "yes",
    purchased_by: "Amir Saeed",
    title: "Studio Executive",
    size: "360",
    floor: "4th Floor",
    number: "6",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/StudioExecutive(350sqft).png",
  },

  {
    id: 37,
    sold: "yes",
    purchased_by: "Rabia Waseem",
    title: "Two Bed Executive",
    size: "982",
    floor: "5th Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/2BedExecutive(959sqft).png",
  },
  {
    id: 38,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "625",
    floor: "5th Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/OneBedDeluxe(596sqft).png",
  },
  {
    id: 39,
    sold: "no",
    purchased_by: "",
    title: "One Bed Executive",
    size: "573",
    floor: "5th Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/OneBedExecutive(575sqft).png",
  },
  {
    id: 40,
    sold: "yes",
    purchased_by: "Muhammad Altaf",
    title: "Studio Deluxe",
    size: "410",
    floor: "5th Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/StudioDeluxe(391sqft).png",
  },

  {
    id: 41,
    sold: "yes",
    purchased_by: "Faisal Shahid",
    title: "Studio Executive",
    size: "360",
    floor: "5th Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/StudioExecutive(350sqft).png",
  },

  {
    id: 42,
    sold: "yes",
    purchased_by: "Sarfaraz Ahmad",
    title: "Two Bed Executive",
    size: "982",
    floor: "6th Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/2BedExecutive.png",
  },
  {
    id: 43,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "625",
    floor: "6th Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/OneBedDeluxe(596sqft).png",
  },

  {
    id: 44,
    sold: "yes",
    purchased_by: "Rao Shahrukh",
    title: "One Bed Executive",
    size: "573",
    floor: "6th Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/OneBedExecutive(575sqft).png",
  },

  {
    id: 45,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "410",
    floor: "6th Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/StudioDeluxe(391sqft).png",
  },
  {
    id: 46,
    sold: "yes",
    purchased_by: "Muhammad Maisam",
    title: "Studio Executive",
    size: "360",
    floor: "6th Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/StudioExecutive(350sqft).png",
  },

  // end here
];

export function getAllResidences() {
  return residences;
}

export function getResidenceById(id) {
  return residences.find((item) => item.id === id);
}

export function getResidenceByType(type) {
  return residences.filter((item) => item.type === type);
}

export function getResidenceByFloor(floor) {
  return residences.filter((item) => item.floor === floor);
}

// for showing the details on homepage image
export function getAvailableResidencesByFloor(floor) {
  return residences.filter((item) => item.floor === floor && item.sold === "no")
    .length;
}
